<?php
/**
 * MessageOptionsModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalCommunicationAdmin
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Communication Administration API
 *
 * Bumbal Communication Server Administration API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BumbalCommunicationAdmin\BumbalCommunicationAdmin\Model;

use \ArrayAccess;

/**
 * MessageOptionsModel Class Doc Comment
 *
 * @category    Class
 * @package     BumbalCommunicationAdmin
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MessageOptionsModel implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'MessageOptionsModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'include_delivery_method_name' => 'bool',
        'include_template_object' => 'bool',
        'include_message_type_name' => 'bool',
        'include_message_content' => 'bool',
        'include_message_history' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'include_delivery_method_name' => null,
        'include_template_object' => null,
        'include_message_type_name' => null,
        'include_message_content' => null,
        'include_message_history' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'include_delivery_method_name' => 'include_delivery_method_name',
        'include_template_object' => 'include_template_object',
        'include_message_type_name' => 'include_message_type_name',
        'include_message_content' => 'include_message_content',
        'include_message_history' => 'include_message_history'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'include_delivery_method_name' => 'setIncludeDeliveryMethodName',
        'include_template_object' => 'setIncludeTemplateObject',
        'include_message_type_name' => 'setIncludeMessageTypeName',
        'include_message_content' => 'setIncludeMessageContent',
        'include_message_history' => 'setIncludeMessageHistory'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'include_delivery_method_name' => 'getIncludeDeliveryMethodName',
        'include_template_object' => 'getIncludeTemplateObject',
        'include_message_type_name' => 'getIncludeMessageTypeName',
        'include_message_content' => 'getIncludeMessageContent',
        'include_message_history' => 'getIncludeMessageHistory'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['include_delivery_method_name'] = isset($data['include_delivery_method_name']) ? $data['include_delivery_method_name'] : null;
        $this->container['include_template_object'] = isset($data['include_template_object']) ? $data['include_template_object'] : null;
        $this->container['include_message_type_name'] = isset($data['include_message_type_name']) ? $data['include_message_type_name'] : null;
        $this->container['include_message_content'] = isset($data['include_message_content']) ? $data['include_message_content'] : null;
        $this->container['include_message_history'] = isset($data['include_message_history']) ? $data['include_message_history'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets include_delivery_method_name
     * @return bool
     */
    public function getIncludeDeliveryMethodName()
    {
        return $this->container['include_delivery_method_name'];
    }

    /**
     * Sets include_delivery_method_name
     * @param bool $include_delivery_method_name
     * @return $this
     */
    public function setIncludeDeliveryMethodName($include_delivery_method_name)
    {
        $this->container['include_delivery_method_name'] = $include_delivery_method_name;

        return $this;
    }

    /**
     * Gets include_template_object
     * @return bool
     */
    public function getIncludeTemplateObject()
    {
        return $this->container['include_template_object'];
    }

    /**
     * Sets include_template_object
     * @param bool $include_template_object
     * @return $this
     */
    public function setIncludeTemplateObject($include_template_object)
    {
        $this->container['include_template_object'] = $include_template_object;

        return $this;
    }

    /**
     * Gets include_message_type_name
     * @return bool
     */
    public function getIncludeMessageTypeName()
    {
        return $this->container['include_message_type_name'];
    }

    /**
     * Sets include_message_type_name
     * @param bool $include_message_type_name
     * @return $this
     */
    public function setIncludeMessageTypeName($include_message_type_name)
    {
        $this->container['include_message_type_name'] = $include_message_type_name;

        return $this;
    }

    /**
     * Gets include_message_content
     * @return bool
     */
    public function getIncludeMessageContent()
    {
        return $this->container['include_message_content'];
    }

    /**
     * Sets include_message_content
     * @param bool $include_message_content
     * @return $this
     */
    public function setIncludeMessageContent($include_message_content)
    {
        $this->container['include_message_content'] = $include_message_content;

        return $this;
    }

    /**
     * Gets include_message_history
     * @return bool
     */
    public function getIncludeMessageHistory()
    {
        return $this->container['include_message_history'];
    }

    /**
     * Sets include_message_history
     * @param bool $include_message_history
     * @return $this
     */
    public function setIncludeMessageHistory($include_message_history)
    {
        $this->container['include_message_history'] = $include_message_history;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\BumbalCommunicationAdmin\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\BumbalCommunicationAdmin\ObjectSerializer::sanitizeForSerialization($this));
    }
}


