<?php
/**
 * ActivityModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalCommunicationAdmin
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Communication Administration API
 *
 * Bumbal Communication Server Administration API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalCommunicationAdmin;

/**
 * ActivityModelTest Class Doc Comment
 *
 * @category    Class */
// * @description ActivityModel
/**
 * @package     BumbalCommunicationAdmin
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ActivityModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ActivityModel"
     */
    public function testActivityModel()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "bumbal_activity_id"
     */
    public function testPropertyBumbalActivityId()
    {
    }

    /**
     * Test attribute "send_invite"
     */
    public function testPropertySendInvite()
    {
    }

    /**
     * Test attribute "send_pref_confirmation"
     */
    public function testPropertySendPrefConfirmation()
    {
    }

    /**
     * Test attribute "send_planned"
     */
    public function testPropertySendPlanned()
    {
    }

    /**
     * Test attribute "send_eta"
     */
    public function testPropertySendEta()
    {
    }

    /**
     * Test attribute "send_executed"
     */
    public function testPropertySendExecuted()
    {
    }

    /**
     * Test attribute "send_cancelled"
     */
    public function testPropertySendCancelled()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }

    /**
     * Test attribute "messages"
     */
    public function testPropertyMessages()
    {
    }

    /**
     * Test attribute "archived"
     */
    public function testPropertyArchived()
    {
    }

    /**
     * Test attribute "archive_data"
     */
    public function testPropertyArchiveData()
    {
    }
}
