<?php
/**
 * MessageModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalCommunicationAdmin
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Communication Administration API
 *
 * Bumbal Communication Server Administration API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalCommunicationAdmin;

/**
 * MessageModelTest Class Doc Comment
 *
 * @category    Class */
// * @description MessageModel
/**
 * @package     BumbalCommunicationAdmin
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MessageModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MessageModel"
     */
    public function testMessageModel()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "delivery_method_id"
     */
    public function testPropertyDeliveryMethodId()
    {
    }

    /**
     * Test attribute "delivery_method_name"
     */
    public function testPropertyDeliveryMethodName()
    {
    }

    /**
     * Test attribute "message_type_id"
     */
    public function testPropertyMessageTypeId()
    {
    }

    /**
     * Test attribute "message_type_name"
     */
    public function testPropertyMessageTypeName()
    {
    }

    /**
     * Test attribute "activity_id"
     */
    public function testPropertyActivityId()
    {
    }

    /**
     * Test attribute "template"
     */
    public function testPropertyTemplate()
    {
    }

    /**
     * Test attribute "scheduled_job"
     */
    public function testPropertyScheduledJob()
    {
    }

    /**
     * Test attribute "provider_id"
     */
    public function testPropertyProviderId()
    {
    }

    /**
     * Test attribute "provider_name"
     */
    public function testPropertyProviderName()
    {
    }

    /**
     * Test attribute "provider_reference"
     */
    public function testPropertyProviderReference()
    {
    }

    /**
     * Test attribute "sent"
     */
    public function testPropertySent()
    {
    }

    /**
     * Test attribute "history"
     */
    public function testPropertyHistory()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }
}
