<?php
/**
 * MessageOptionsModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalCommunicationAdmin
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Communication Administration API
 *
 * Bumbal Communication Server Administration API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalCommunicationAdmin;

/**
 * MessageOptionsModelTest Class Doc Comment
 *
 * @category    Class */
// * @description MessageOptionsModel
/**
 * @package     BumbalCommunicationAdmin
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MessageOptionsModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MessageOptionsModel"
     */
    public function testMessageOptionsModel()
    {
    }

    /**
     * Test attribute "include_delivery_method_name"
     */
    public function testPropertyIncludeDeliveryMethodName()
    {
    }

    /**
     * Test attribute "include_template_object"
     */
    public function testPropertyIncludeTemplateObject()
    {
    }

    /**
     * Test attribute "include_message_type_name"
     */
    public function testPropertyIncludeMessageTypeName()
    {
    }

    /**
     * Test attribute "include_message_content"
     */
    public function testPropertyIncludeMessageContent()
    {
    }

    /**
     * Test attribute "include_message_history"
     */
    public function testPropertyIncludeMessageHistory()
    {
    }
}
