<?php
/**
 * MessageModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalCommunicationAdmin
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Communication Administration API
 *
 * Bumbal Communication Server Administration API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalCommunicationAdmin;

/**
 * MessageModelTest Class Doc Comment
 *
 * @category    Class */
// * @description MessageModel
/**
 * @package     BumbalCommunicationAdmin
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MessageModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "MessageModel"
     */
    public function testMessageModel()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "delivery_method_id"
     */
    public function testPropertyDeliveryMethodId()
    {

    }

    /**
     * Test attribute "delivery_method_name"
     */
    public function testPropertyDeliveryMethodName()
    {

    }

    /**
     * Test attribute "message_type_id"
     */
    public function testPropertyMessageTypeId()
    {

    }

    /**
     * Test attribute "message_type_name"
     */
    public function testPropertyMessageTypeName()
    {

    }

    /**
     * Test attribute "activity_id"
     */
    public function testPropertyActivityId()
    {

    }

    /**
     * Test attribute "template"
     */
    public function testPropertyTemplate()
    {

    }

    /**
     * Test attribute "scheduled_job"
     */
    public function testPropertyScheduledJob()
    {

    }

    /**
     * Test attribute "provider_id"
     */
    public function testPropertyProviderId()
    {

    }

    /**
     * Test attribute "provider_name"
     */
    public function testPropertyProviderName()
    {

    }

    /**
     * Test attribute "provider_reference"
     */
    public function testPropertyProviderReference()
    {

    }

    /**
     * Test attribute "sent"
     */
    public function testPropertySent()
    {

    }

    /**
     * Test attribute "history"
     */
    public function testPropertyHistory()
    {

    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {

    }

}
