<?php
/**
 * MappingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalCommunicationAdmin
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Communication Administration API
 *
 * Bumbal Communication Server Administration API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalCommunicationAdmin;

use \BumbalCommunicationAdmin\Configuration;
use \BumbalCommunicationAdmin\ApiClient;
use \BumbalCommunicationAdmin\ApiException;
use \BumbalCommunicationAdmin\ObjectSerializer;

/**
 * MappingApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalCommunicationAdmin
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MappingApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createMapping
     *
     * Create a Mapping.
     *
     */
    public function testCreateMapping()
    {
    }

    /**
     * Test case for deleteMapping
     *
     * Delete a mapping.
     *
     */
    public function testDeleteMapping()
    {
    }

    /**
     * Test case for retrieveListMapping
     *
     * Retrieve List of Mapping.
     *
     */
    public function testRetrieveListMapping()
    {
    }

    /**
     * Test case for retrieveMapping
     *
     * Retrieve a mapping.
     *
     */
    public function testRetrieveMapping()
    {
    }

    /**
     * Test case for updateMapping
     *
     * Update an mapping.
     *
     */
    public function testUpdateMapping()
    {
    }
}
