<?php
/**
 * MessagevariablesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalCommunicationAdmin
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Communication Administration API
 *
 * Bumbal Communication Server Administration API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalCommunicationAdmin;

use \BumbalCommunicationAdmin\Configuration;
use \BumbalCommunicationAdmin\ApiClient;
use \BumbalCommunicationAdmin\ApiException;
use \BumbalCommunicationAdmin\ObjectSerializer;

/**
 * MessagevariablesApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalCommunicationAdmin
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MessagevariablesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createMessageVariable
     *
     * Create a MessageVariable.
     *
     */
    public function testCreateMessageVariable()
    {

    }

    /**
     * Test case for deleteMessageVariable
     *
     * Delete a message variables.
     *
     */
    public function testDeleteMessageVariable()
    {

    }

    /**
     * Test case for retrieveListMessageVariables
     *
     * Retrieve List of Message Variables.
     *
     */
    public function testRetrieveListMessageVariables()
    {

    }

    /**
     * Test case for retrieveMessageVariable
     *
     * Retrieve a message variable.
     *
     */
    public function testRetrieveMessageVariable()
    {

    }

    /**
     * Test case for updateMessageVariable
     *
     * Update an MessageVariable.
     *
     */
    public function testUpdateMessageVariable()
    {

    }

}
