<?php
/**
 * TemplateApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalCommunicationAdmin
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Communication Administration API
 *
 * Bumbal Communication Server Administration API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalCommunicationAdmin;

use \BumbalCommunicationAdmin\Configuration;
use \BumbalCommunicationAdmin\ApiClient;
use \BumbalCommunicationAdmin\ApiException;
use \BumbalCommunicationAdmin\ObjectSerializer;

/**
 * TemplateApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalCommunicationAdmin
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TemplateApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createTemplate
     *
     * Create a Template.
     *
     */
    public function testCreateTemplate()
    {
    }

    /**
     * Test case for deleteTemplate
     *
     * Delete a Template.
     *
     */
    public function testDeleteTemplate()
    {
    }

    /**
     * Test case for retrieveListTemplate
     *
     * Retrieve List of Templates.
     *
     */
    public function testRetrieveListTemplate()
    {
    }

    /**
     * Test case for retrieveTemplate
     *
     * Retrieve a Template.
     *
     */
    public function testRetrieveTemplate()
    {
    }

    /**
     * Test case for updateTemplate
     *
     * Update an Template.
     *
     */
    public function testUpdateTemplate()
    {
    }
}
